### PR TITLE
use Bytes.t as data type for IPv6 addresses

### PR DESCRIPTION
**Pull request by verbosemode**
* this PR is a proposal to addresses issue #16
* I didn't touch any parsing functions, but migrated auxiliary functions to operate on Bytes. If this was over the top, I could cut this PR down to the essential parts and keep the rest for later.
* I've resorted to imperative code due to the index based set functions of Bytes

### CODE REVIEW

**Comment by verbosemode** [comment]
The current build failures are mainly due to unused functions in the B128 module. But maybe it is a good idea to keep them for future PRs.

**Comment by hannesm** [comment]
I like the code changes, thanks a lot! :)

I pushed a commit which removes some unused bindings -- if we need them at a later point, we can add them then :)

Does this code fix #113 as a side-effect? Would be great to have it double-checked by @RyanGibb, and maybe have a test case?

**Comment by RyanGibb** [comment]
I can confirm that this fixed https://github.com/mirage/ocaml-ipaddr/issues/113. Thanks @verbosemode !

**Comment by hannesm** [comment]
@RyanGibb cool, great. Could you PR a test case for that issue you uncovered?

**Comment by hannesm** [comment]
> @RyanGibb cool, great. Could you PR a test case for that issue you uncovered?

Sorry for the noise, while at this PR, I pushed [5c4a09b](https://github.com/mirage/ocaml-ipaddr/pull/115/commits/5c4a09b0282cb68852bfa78cc4787583b8723ee0) as a test for your observed failure. This fails on the main branch, and succeeds on this branch.

I'd move on to merge this PR (today or tomorrow) and cut a release, what do others think? @RyanGibb @avsm

**Comment by RyanGibb** [comment]
Apparently at the exact same minute as you commented I also opened a pr https://github.com/mirage/ocaml-ipaddr/pull/116/files 😄 I'm happy to go with your test though. The only thing is perhaps it would be better to use the address `0:0:8000:0:0:0:0:0` as it's the simplest address that exhibits the problematic behavior, and because `2a01:4f9:c011:87ad:0:0:0:0` is actually the address of my own server.

**Comment by hannesm** [comment]
@RyanGibb I added the 0:0:800:: test case as well.

**Pull request merged**
