### PR TITLE
use domain-name library to produce domain names from ip addresses

### LINKED ISSUE #53: Ipaddr.to_domain_name returns an empty label
See: https://github.com/mirage/ocaml-ipaddr/blob/master/lib/ipaddr.ml#L227

I assume that the empty string was intended to signify an FQDN to distinguish it from a PQDN, but Dns.Name.marshal does not check for empty strings, leading it to encode two zero labels in the packet, which is invalid and cannot be parsed. I found this while writing a unit test for Mdns_resolver_mirage.gethostbyaddr, but Dns_resolver_mirage.gethostbyaddr has the same bug.

I'll raise a separate issue in ocaml-dns to discuss related points.

### PR DESCRIPTION
**Pull request by hannesm**
fixes #53

### CODE REVIEW

**Comment by dinosaure** [comment]
I'm fine with this, but I'm aware by this update:

```diff
 -     "e.0.0.2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.0.9.0.0.4.0.5.4.1.0.0.a.2.ip6.arpa."
 +     "e.0.0.2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.0.9.0.0.4.0.5.4.1.0.0.a.2.ip6.arpa"
```

in tests. So I don't know about internals of `domain-name` and believe that it's work perfectly but it's a breaking change or not?

**Comment by hannesm** [comment]
(I just added a `of_domain_name` in here as well).

@dinosaure this is a breaking API change (though I couldn't find any users of `to_domain_name`)! mainly because the result are different now, it used to be: `to_domain_name : t -> string list`, now it is ``to_domain_name : t -> [`host] Domain_name.t``.

If you want your trailing `.` back, you can use https://hannesm.github.io/domain-name/doc/domain-name/Domain_name/index.html#val-to_string with `~trailing:true`.

this also superseeds #54 if accepted (which contains some discussion about trailing dots or not)

**Comment by avsm** [comment]
This lgtm; I can release with a major number bump to reflect the API change.

@hannesm would you be willing to also move domain-name into the mirage/ org so that we have all the dependencies in one place?

**Comment by dinosaure** [comment]
@avsm can we integrate to this major release #84 ?

**Comment by hannesm** [comment]
@avsm before doing a release, I'd prefer to clean up #35 / #37 -- `val to_bytes : t -> string` is just confusing every time i need to use it.

> to have all the dependencies in one place

I'm not sure I follow, does this mean to move sexplib and astring and fmt also to the mirage org?

I'm fine with moving domain-name to mirage, but would prefer to have some guidelines about maintainership _before_ doing this (see https://github.com/mirage/ocaml-dns/issues/163 https://github.com/mirage/mirage-www/pull/562), I'm a bit worried about increasing the number of repositories in the mirage organisation without having maintainers explicitly.

the other reason to not move it is due to travis CI which has n runners per organisation/user.

**Comment by hannesm** [comment]
@dinosaure did you mean #87?

**Comment by dinosaure** [comment]
I yes sorry #87 👍

**Comment by avsm** [comment]
Ok, let's separate the repo move of domain-name discussion for elsewhere; it's not material to this particular PR if it's not an immediate change. 

#87 can go in the major bump release as well indeed.

**Pull request merged**
