### PR TITLE
Add IPv4/6 conversions from/to Cstructs

### PR DESCRIPTION
**Pull request by nojb**
Re #12

### CODE REVIEW

**Comment by yomimono** [comment]
Any chance this will go in anytime soon?  I'm working on something which will need either this or some overrides like those required for @nojb 's ipv6 patch (which are still in place).

**Comment by nojb** [comment]
I seem to remember that a little refactoring was necessary to make all the possible conversions fit more seamlesssly, with less code duplication and with an uniform interface (maybe in the style of ocplib-endian).

Until this is done you may be better off including the necessary functions in your code I guess :(

**Comment by samoht** [comment]
@dsheets any opinion on that PR?

**Comment by dsheets** [comment]
This needs refactoring/renaming work that will likely break backward compat of the interface. Analysis/suggestions/PRs very welcome for that.

**Comment by avsm** [comment]
It only took 2.5 years, but https://github.com/mirage/ocaml-cstruct/pull/133 has significantly reduced the dependency cone of the cstruct library.  So depending on it directly from ipaddr is now feasible

**Comment by avsm** [comment]
It took half a decade, but fixed in #90 based on this PR

**Pull request closed without merging**
