### PR TITLE
require ppx_sexp_conv < v0.11.0

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by cfcs** [comment]
I'm not happy with the way this dependency is being bounded in dozens of opam packages these days.
If the maintainer of `pp_sexp_conv` won't unbreak their package, shouldn't we just remove the dependency?

**Comment by samoht** [comment]
v0.11.1 has been fixed, we can use that instead (and/or remove v0.11.0 from the repository)

**Comment by cfcs** [comment]
@samoht that's great!

@hannesm would you mind changing your PR to exclude `v.0.11.0` specifically, so people can use lower/higher versions? It appears to me that will cause less breakage than forcing everyone to use the old version.

**Comment by hannesm** [comment]
from what I understand (looking into the `jbuilder` file here), there needs to be adjustments made since `ppx_sexp_conv` > v0.11.0 requires a runtime dependency.  the issue looks a bit more tricky since ipaddr requires `>=4.03.0`, whereas the newest `ppx_sexp_conv` require `>=4.04.1`.  I won't have time for this this week.

**Pull request closed without merging**
