### PR TITLE
store CIDR in Prefix.t (do not mask out non-prefix bits)

### LINKED ISSUE #96: is there a type to store "ip in this network"?
when configuring and storing IP addresses, I would like to have a type to put the IP address and the subnet mask -- i.e. `Ipaddr.V4.t * int` -- but given the `Prefix` submodules, I was hoping to find a `Ipaddr.V4.t * Ipaddr.V4.Prefix.t` where the invariant that the ip address (first projection) is a member in the network (second projection), but I fail to find such a type. The `Prefix.of_address_string` constructs such a type (which does not carry that invariant along). Would be great to have this in a next release (unless it is already there).

### PR DESCRIPTION
**Pull request by hannesm**
this fixes #96.

This is an API breaking change: `Prefix.of_string` (and `Prefix.make` etc.) no longer lose any information, but preserve the entire address in the first projection.
This gives rise to:
- of_address_string/of_address_string_exn,to_address_string,to_address_buffer are deprecated now (use of_string/of_string_exn/to_string/to_buffer instead)
- prefix: t -> t which zeroes out the non-prefix bits in the address of t
- address: t -> addr, the first projection of the cidr

I checked opam-released packages and could not find any that depends on the old behaviour (there may be unreleased packages that do). once this is merged and released, mirage & mirage-tcpip can be simplified (use a Prefix.t instead of a pair of t * Prefix.t).

I'm still undecided whether the module Prefix should be renamed to Cidr or not (an alias may do the trick, but then I'm not sure whether it is worth it).

### CODE REVIEW

**Comment by hannesm** [comment]
I wonder slightly about deprecation and backwards compatibility -- since this changes the semantics (of `Prefix.t`), I think it is not worth to mark functions as deprecated (instead, remove them -- so we'll spot callers and be able to upper bound them / port them forward). WDYT?

**Comment by verbosemode** [comment]
> I'm still undecided whether the module Prefix should be renamed to Cidr or not (an alias may do the trick, but then I'm not sure whether it is worth it).

Sorry for just chiming in for the bikeshed :-) I think Prefix is fine for the module name. In networking people often talk about "how many prefixes are currently in the BGP table" for example. Just quoting from the CIDR RFC https://tools.ietf.org/html/rfc4632#section-3.1:

> In CIDR notation, a **prefix** is shown as a 4-octet quantity, just like a traditional IPv4 address or network number, followed by the "/" (slash) character, followed by a decimal value between 0 and 32 that describes the number of significant bits.

Python on the other hand has IPv4Address, IPv6Address, IPv4Network and IPv6Network as main classes for working with addresses and networks in the ipaddress module. Maybe this could be also an option if the module name should be be changed. Ipaddr.V4.Net or Ipaddr.V4.Network

**Comment by avsm** [comment]
The name `Prefix` is fine by me.  I agree with @hannesm about the warnings -- the deprecation warnings simply delay the inevitable build failure when using the result, so we might as well remove them and bump the major version, with clear documentation on how to port it. They are relatively rarely used functions compared to the main `Ipaddr` module to my knowledge.

**Comment by hannesm** [comment]
@avsm cool, there are indeed few users of `Ipaddr.YY.Prefix`. I pushed 53fc6dd which remove these functions and add a changes entry. if this is fine with you, I'd be keen to cut a release with this PR merged.

**Comment by hannesm** [comment]
@verbosemode thanks for your investigation. I'll stick with `Prefix` (module rename always has a cost, and if `Prefix` is fine for networking people, let's just continue to use it).

**Comment by hannesm** [comment]
FWIW, I ported mirage (and mirage-runtime) to these changes https://github.com/hannesm/mirage/tree/ipaddr-5, and tcpip as well https://github.com/hannesm/mirage-tcpip/tree/ipaddr-5.0.0

I also pushed some upper bounds for mirage & mirage-runtime to opam-repository https://github.com/ocaml/opam-repository/pull/16640 -- a full e2e test with these changes looks promising :) (imho the commits above show that the code gets easier - (due to at least fewer lines of code and less duplicate information)).

**Pull request merged**
