### PR TITLE
add subset_eq operation to Prefix modules

### PR DESCRIPTION
**Pull request by seliopou**

### CODE REVIEW

**Comment by hannesm** [comment]
is `subset_eq` really the right name here? isn't the relation rather subnet inclusion? `eq` reminds me too much of `equality`, which isn't the case here..

**Comment by seliopou** [comment]
Have at it with the names. The `eq` tacked on to the end is to indicate that if `a = b`, then `subset_eq a b = true`. In other words it's `⊆`, rather than `⊂`.

**Comment by dsheets** [comment]
This is a nice and thorough contribution. I have two comments:

1. My understanding is that "subset" without qualifier refers to exactly `⊆` with `⊂` known as "proper subset". If this is the case, I think it's safe to just call this `subset`.
2. Is the argument order of smaller-larger the logical one? For some reason, larger-smaller seems more intuitive to me but I don't have a good grasp on why. One argument for larger-smaller is currying:
`let is_subnet_legit = subset legit_net`. Of course, `mem` has the smaller-larger order so maybe it is best to stay with that for consistency. Once an argument order is selected, it will be extremely difficult to change without a full interface refactor due to type equality and confusion. As both of the arguments are the same type, perhaps labeled arguments would help here (and eliminate the currying/order issue)?

**Comment by seliopou** [comment]
The name of the operation was changed to `subset` in c2e483f.

On the second issue, this is always a huge pain to keep straight. My rule of thumb is that for constructors, the "base value" goes last, and for destructors, the destructed value goes first. `subset` as written conforms to this rule, as it's a destructor of the first argument; `subset`-ness" is a property of the first argument rather than the second.

Having said that, labeling one of the arguments would probably be a good idea. Not sure what to name it tho.

**Comment by dsheets** [comment]
`prefix` (for larger)? `subnet` (for smaller)? I'd like to merge this but the argument order/labeling is blocking that.

**Comment by mor1** [comment]
As a bystander, FWIW, etc... `subset x y = true` suggests `x ⊆ y` to me (`x` is a subset of `y`); and `subnet`/`supernet` perhaps?!

**Comment by seliopou** [comment]
Cleanup time. How should the argument be labeled?

**Pull request closed without merging**
