### PR TITLE
V4.Prefix.broadcast/last yield incorrect result for /32 prefixes.

### PR DESCRIPTION
**Pull request by verbosemode**
This issue is similar to #98. The function V4.Prefix.broadcast calls Int32.shift_right_logical ( >|> ), which has undefined behavior for ints >= 32.

V4.Prefix.of_string_exn "192.168.0.0/32" |> V4.Prefix.broadcast results in 255.255.255.255 for example. However 192.168.0.0 would be the correct result. The issue affects V4.Prefix.last as well because it calls the broadcast function.

The implementation is based on Python's [ipaddress](https://github.com/python/cpython/blob/3.8/Lib/ipaddress.py#L710-L716) module.

### CODE REVIEW

**Comment by hannesm** [comment]
I agree with your changes, thanks for adding tests. I pushed a commit to make the ocamlformat CI pass, and will look into the 32bit failure soon(ish).

**Comment by hannesm** [comment]
@NightBlues is the change of the semantics of B128.shift_right fine with you? It now errors if sz < 0 || sz > 128 (see 8ffe58e) due to issues on 32bit systems.

**Comment by NightBlues** [comment]
@hannesm condition `if sz < 0 || sz > 128` looks good to me.
@verbosemode I understand that this code was not written this way purposely, but 

> V4.Prefix.of_string_exn "192.168.0.0/32" |> V4.Prefix.broadcast results in 255.255.255.255 for example.

may be a correct result for example for /31 networks https://tools.ietf.org/html/rfc3021 says:

> The 255.255.255.255 IP broadcast address MUST be used for
>       broadcast Address Mask Replies in point-to-point links with 31-bit
>       subnet masks

while /31 has only 2 addresses p2p is the only purpose for it

**Comment by verbosemode** [comment]
> may be a correct result for example for /31 networks https://tools.ietf.org/html/rfc3021 says:
> 
> > The 255.255.255.255 IP broadcast address MUST be used for
> > broadcast Address Mask Replies in point-to-point links with 31-bit
> > subnet masks
> 
> while /31 has only 2 addresses p2p is the only purpose for it
> 
> I mean may be we should signal an error?

Thanks for the pointer. Good catch. I didn't read the RFC on /31 for this PR to be honest and just checked on what Python is doing.

```
>>> IPv4Network("192.168.0.0/32").broadcast_address
IPv4Address('192.168.0.0')

>>> IPv4Network("192.168.0.0/31").broadcast_address
IPv4Address('192.168.0.1')
```

[Rust's IPv4Net](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e97250f89460a6a255f114c724b1214e) module seems to behave in the same way.

From a computation perspective I would say that the current code should be okay. Maybe it would be the responsibility of an application developer to use the correct broadcast address and act according to the RFC.

**Pull request merged**
