### PR TITLE
Adds pp functions and deprecation warnings for pp_hum

### LINKED ISSUE #59: API inconsistency: no Macaddr.pp_hum
we have a to_string, but we should provide a pretty printer, shouldn't we?

### PR DESCRIPTION
**Pull request by verbosemode**
This would close #59

### CODE REVIEW

**Comment by hannesm** [comment]
lgtm. I'd be in favour of breaking the API and rename `pp_hum` to `pp` in this library (and introduce only `Macaddr.pp`).

**Comment by verbosemode** [comment]
I talked to Kate yesterday and she said the build failures are related to some issues with the Docker images.

**Comment by jpdeplaix** [comment]
This PR should fix the issue with Travis once merged and released: https://github.com/ocaml/dbm/pull/5

**Comment by kit-ty-kate** [comment]
This got merged an released a few days ago so if anybody relaunches Travis it shouldn't fail this time.

**Comment by hannesm** [comment]
@kit-ty-kate thx for reminding, i relaunched the travis jobs here

**Comment by hannesm** [comment]
thanks, sorry for the delay!

**Pull request merged**
